### ISSUE TITLE
[feature request]  comment at a specific position

### ISSUE THREAD

**Issue by Elijah-29** [numToStr/Comment.nvim#155]
![](https://user-images.githubusercontent.com/102277445/165785545-543d6b35-21ac-49ca-8d65-8b9d0029719c.png)

I wonder if there's something like emacs's comment-column in Neovim or this plugin.
Is it possible for us to implement it?

**Comment by numToStr** [comment]
> I wonder if there's something like emacs's comment-column in Neovim

I have no idea about it neither I understood it from the screenshot, sorry.

> Is it possible for us to implement it?

It depends on the usefulness of it.

**Comment by Elijah-29** [comment]
![Screen Shot 2022-04-29 at 06 32 46](https://user-images.githubusercontent.com/102277445/165858770-61178f7b-88a4-4f26-86eb-841379f5b09e.png)

**Comment by numToStr** [comment]
Thanks for the explanation. Now I understood your feature request.

This looks interesting but in hindsight, I doubt its usefulness. Because most of the time you are using a formatter of some kind and any good formatter will trim the space to only one or something (depending on your formatter/lang).
