### ISSUE TITLE
[Bug] Wrong block comment on visual line mode

### ISSUE THREAD

**Issue by jjant** [numToStr/Comment.nvim#224]
## Description

Hi, forgive me if this is just me expecting the wrong thing, but in this rust file:

```rust
fn f() {}
```

If I select the line with the function and comment block: `Vgb`, I get this:
```rust
/*  */fn f() {}
```

When I expected:
```rust
/* fn f() {} */
```

Line comment mode works as I expect it: `Vgc` results in `// fn f() {}`.

## Note
The _wrong_ behaviour seems to happen when **selecting exactly 1 line**, if I select more, I get what I expect:

```rust
fn f() {
    something();
}

// V2jgb

/* fn f() {
    something();
} */
```

**Comment by numToStr** [comment]
Reproduced. I'll have a look. Thanks for reporting.

**Comment by numToStr** [comment]
The reason for this bug is when you enter `VISUAL LINE` mode, in our case, `'<` and `'>` mark gives you `0` and `2147483647` respectively and we are using `string.sub({line}, 0, 2147483647 + 1)` to get the substring but LuaJIT implementation of `string.sub` return empty string because of interger casting in luajit code itself. So, we have handle this ourselves.

Ref https://github.com/LuaJIT/LuaJIT/issues/674

**Comment by jjant** [comment]
Nice find, @numToStr!

**Comment by numToStr** [comment]
Hopefully 70615e63a6dcc41de0e90a7d79bdcec511bda93f fixes this issue :)
