### ISSUE TITLE
Apache vs. Nginx are commented differently?

### ISSUE THREAD

**Issue by dubgeiser** [numToStr/Comment.nvim#264]
Hi, I'm experiencing behavior that I'm not sure what to attribute it to:

If I open an Apache configuration file, Neovim recognizes this as "apache" and when I use `gcc` to comment a line, Comment.nvim uses the block comment `/* */`, which is incorrect, should be `#`

I wanted to open a PR to support Apache and then I thought I'd include Nginx too, because both were not in `ft.lua`.
But before I did that, I also tested an nginx.conf file:
Neovim recognizes this as "nginx", but when I wanted to comment a line, Comment.nvim, correctly, used `#`

So, this puzzles me a bit; both file types are not in `ft.lua`, yet one behaves correctly while the other doesn't, is this actually attributable to Comment.nvim?  If IRCC; Neovim's filetype detection system has been revised (I'm on nightly) and maybe that has got something to do with it?

**Comment by numToStr** [comment]
As you've already figured out that all these filetypes are not listed in `ft.lua`, thus not supported by `Comment.nvim`.

The incorrect behavior you are seeing is because of `:h 'commentstring'` having wrong value for `apache` filetype. To resolve this (the correct way), make a PR to vim to fix the commentstring for apache, then nvim will pull the patches from vim.

**Comment by dubgeiser** [comment]
https://github.com/vim/vim/pull/11422
