### ISSUE TITLE
`gqq` to break long lines is broken

### ISSUE THREAD

**Issue by jan-xyz** [numToStr/Comment.nvim#379]
I disabled my plugins one-by-one and it seems that this plugin breaks `gqq` which should break long lines down to the column width. Do you have an idea what might be going wrong?

**Comment by andres-lowrie** [comment]
So I had this same issue, and after I uninstalled this plugin to test, I was still facing it. I think the problem is with _lsp-config_ however

`:h lsp-config`

shows the following
```vimdoc
formatexpr' is set to |vim.lsp.formatexpr()| if both 'formatprg' and
  'formatexpr' are empty. This allows to format lines via |gq| if the language
  server supports it.
```

and for me `formatprg` is empty but `formatexpr` is not
```
:set formatexpr
:set formatprg

# the expression is set to
formatexpr=v:lua.vim.lsp.formatexpr()
```

so I'm thinking this is a problem with lsp and how I have that configured and not this plugin given the test I did by uninstalling it and also quickly looking at the mappings be set by this plugin `gq` isn't mentioned anywhere, so I'm leaning towards lsp

Hope that helps and lmk if you find a solve for this

----

also. When I do `gww` instead of `gqq` it kinda works but it's not respecting the column width, I'm diving through the docs to try and understand how all the things interplay... muscle memory is too strong to change 😂

**Comment by jan-xyz** [comment]
Thanks for the hint! I dug a bit deeper and in the same doc it says: 

> - Q: How can I disable LSP formatting when using the |gq| command?
  A: To use the default internal formatting method and bypass the LSP client's
  'formatexpr', use |gw| instead.
  Alternatively you can completely disable LSP formatting with gq by
  unsetting 'formatexpr':
>
> ```lua
>    vim.api.nvim_create_autocmd('LspAttach', {
>        callback = function(args)
>            vim.bo[args.buf].formatexpr = nil
>        end,
>    })
> ```

Doing the suggestion from the docs works for me!
